name = "beacon"
handle = "beacon"
client_id = "REPLACE_WITH_CLIENT_ID"
application_url = "https://REPLACE_WITH_WEB_APP_HOST"
embedded = true

[access_scopes]
scopes = "write_pixels,read_customer_events"

[auth]
redirect_urls = [
  "https://REPLACE_WITH_WEB_APP_HOST/shopify/callback"
]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/shopify/webhooks"

[[webhooks.subscriptions]]
topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "/shopify/webhooks"
compliance_topics = true
