name = "beacon"
client_id = "2f1de39dca0e8d0b04ae7d67607d836a"
application_url = "https://beacon-web.swapkats.workers.dev"
embedded = true

[access_scopes]
scopes = "write_pixels,read_customer_events"

[build]

[auth]
redirect_urls = [
  "https://beacon-web.swapkats.workers.dev/shopify/callback"
]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/shopify/webhooks"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "/shopify/webhooks"
